#!/usr/bin/env python3
"""Convert 29-joint trajectory NPZ files into SONIC deploy CSV references.

The C++ deploy (``MotionDataReader::ReadFromCSV``) reads CSV folders only, so any
NPZ has to be materialised as one before ``deploy.sh --motion-data`` can play it.
This script does that conversion in bulk.

Expected NPZ keys
-----------------
``joint_pos``  (N, 29) joint angles, **MuJoCo order** (as written by the tools in
               this directory; set ``--joint-order isaaclab`` if yours differ)
``base_pos``   (N, 3) pelvis position
``base_quat``  (N, 4) pelvis quaternion, wxyz
``fps``        optional scalar; defaults to ``--fps`` (50)

Everything else in the NPZ is ignored. Body poses, velocities and
``metadata.txt`` are regenerated by forward kinematics, so the output always
matches what the deploy expects.

Usage
-----
    # one file
    python gear_sonic_planner/scripts/npz_to_reference.py planner/test_traj/grasp.npz

    # a whole directory of trajectories
    python gear_sonic_planner/scripts/npz_to_reference.py planner/test_traj/

    # custom output root
    python gear_sonic_planner/scripts/npz_to_reference.py traj/*.npz --out-root /tmp/refs
"""

from __future__ import annotations

import argparse
from pathlib import Path
import sys

import numpy as np

sys.path.insert(0, str(Path(__file__).resolve().parent))
from run_wholebody_replay import (  # noqa: E402
    DEPLOY_FPS,
    MJ_TO_IL,
    angular_velocities,
    central_diff,
    mujoco_to_isaaclab,
    resample_qpos,
    run_fk,
    write_reference,
)

REPO_ROOT = Path(__file__).resolve().parents[2]
DEFAULT_OUT_ROOT = REPO_ROOT / "gear_sonic_planner" / "reference"

# MuJoCo (MJCF) joint order for the 29 actuated body joints.
MJ29_NAMES = [
    "left_hip_pitch_joint", "left_hip_roll_joint", "left_hip_yaw_joint", "left_knee_joint",
    "left_ankle_pitch_joint", "left_ankle_roll_joint",
    "right_hip_pitch_joint", "right_hip_roll_joint", "right_hip_yaw_joint", "right_knee_joint",
    "right_ankle_pitch_joint", "right_ankle_roll_joint",
    "waist_yaw_joint", "waist_roll_joint", "waist_pitch_joint",
    "left_shoulder_pitch_joint", "left_shoulder_roll_joint", "left_shoulder_yaw_joint",
    "left_elbow_joint", "left_wrist_roll_joint", "left_wrist_pitch_joint", "left_wrist_yaw_joint",
    "right_shoulder_pitch_joint", "right_shoulder_roll_joint", "right_shoulder_yaw_joint",
    "right_elbow_joint", "right_wrist_roll_joint", "right_wrist_pitch_joint", "right_wrist_yaw_joint",
]


def convert(npz_path: Path, out_root: Path, fps_fallback: float, joint_order: str) -> Path:
    with np.load(npz_path, allow_pickle=False) as data:
        missing = [k for k in ("joint_pos", "base_pos", "base_quat") if k not in data.files]
        if missing:
            raise KeyError(f"{npz_path.name} is missing {missing}; found {sorted(data.files)}")
        jp = np.asarray(data["joint_pos"], dtype=np.float64)
        bp = np.asarray(data["base_pos"], dtype=np.float64)
        bq = np.asarray(data["base_quat"], dtype=np.float64)
        fps = float(data["fps"]) if "fps" in data.files else fps_fallback
        names = [str(x) for x in data["joint_names"]] if "joint_names" in data.files else None

    if jp.ndim != 2 or jp.shape[1] != 29:
        raise ValueError(f"{npz_path.name}: expected joint_pos (N, 29), got {jp.shape}")
    if bp.shape != (len(jp), 3) or bq.shape != (len(jp), 4):
        raise ValueError(f"{npz_path.name}: base_pos/base_quat must match {len(jp)} frames")
    for name, arr in (("joint_pos", jp), ("base_pos", bp), ("base_quat", bq)):
        if not np.isfinite(arr).all():
            raise ValueError(f"{npz_path.name}: {name} contains non-finite values")

    if len(jp) < 10:
        print(f"{npz_path.name:<24} WARNING: only {len(jp)} frames — degenerate path "
              f"(planner returned little more than start+goal); playback will be a jump")

    # Prefer explicit joint names when they are real MJCF names; fall back to the
    # declared ordering otherwise.
    if names and set(names) == set(MJ29_NAMES):
        jp = jp[:, [names.index(n) for n in MJ29_NAMES]]
    elif joint_order == "isaaclab":
        jp = jp[:, MJ_TO_IL]

    qpos = np.zeros((len(jp), 36))
    qpos[:, 0:3] = bp
    qpos[:, 3:7] = bq
    qpos[:, 7:] = jp

    n_in = len(qpos)
    qpos = resample_qpos(qpos, fps, DEPLOY_FPS)
    body_pos, body_quat, _ = run_fk(qpos)

    joint_pos = mujoco_to_isaaclab(qpos[:, 7:])
    name = npz_path.stem
    out_dir = out_root / name / name
    write_reference(
        out_dir, name, joint_pos, central_diff(joint_pos, DEPLOY_FPS), body_pos, body_quat,
        central_diff(body_pos, DEPLOY_FPS), angular_velocities(body_quat, DEPLOY_FPS),
    )
    rate = "" if abs(fps - DEPLOY_FPS) < 1e-9 else f" (resampled {fps:g}->{DEPLOY_FPS:g} Hz)"
    print(f"{npz_path.name:<24} {n_in:4d} -> {len(qpos):4d} frames{rate}   pelvis z "
          f"{body_pos[:, 0, 2].min():.3f}..{body_pos[:, 0, 2].max():.3f} m")
    return out_root / name


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("inputs", type=Path, nargs="+", help=".npz files, or directories containing them")
    ap.add_argument("--out-root", type=Path, default=DEFAULT_OUT_ROOT,
                    help="parent folder for the generated reference dirs")
    ap.add_argument("--fps", type=float, default=DEPLOY_FPS, help="fallback rate when the NPZ has no 'fps'")
    ap.add_argument("--joint-order", choices=("mujoco", "isaaclab"), default="mujoco",
                    help="joint order inside the NPZ (default: mujoco)")
    args = ap.parse_args()

    files: list[Path] = []
    for item in args.inputs:
        if item.is_dir():
            files.extend(sorted(item.glob("*.npz")))
        elif item.suffix == ".npz":
            files.append(item)
        else:
            raise ValueError(f"not an .npz or directory: {item}")
    if not files:
        raise SystemExit("no .npz files found")

    out_root = args.out_root.resolve()
    made = []
    for f in files:
        try:
            made.append(convert(f.resolve(), out_root, args.fps, args.joint_order))
        except Exception as exc:                      # keep going through a batch
            print(f"{f.name:<24} SKIPPED: {exc}")

    if not made:
        raise SystemExit("nothing converted")
    deploy_dir = REPO_ROOT / "gear_sonic_deploy"
    print(f"\n{len(made)} reference folder(s) under {out_root}")
    print(f"\nRun from {deploy_dir}:")
    for d in made:
        try:
            rel = d.relative_to(deploy_dir)
        except ValueError:
            rel = Path("..") / d.relative_to(REPO_ROOT)
        print(f"  ./deploy.sh --motion-data {rel}/ sim")


if __name__ == "__main__":
    main()
